# Generated by Django 2.2.4 on 2019-08-09 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0002_auto_20190808_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='relatives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
