# Generated by Django 2.2.4 on 2019-08-11 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0003_auto_20190809_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='relatives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(unique=True), blank=True, size=None),
        ),
    ]
