# Generated by Django 2.2.4 on 2019-08-13 15:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0004_auto_20190811_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='relatives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
