# Generated by Django 2.2.4 on 2019-08-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0006_auto_20190813_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
